# Generated by Django 4.2.29 on 2026-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needylocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='meals_needed',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='name',
            field=models.CharField(default='Unnamed Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='urgency',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50),
        ),
    ]
