# Generated by Django 4.2.29 on 2026-03-20 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_needylocation_is_active_needylocation_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='proof_after',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='proof_before',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_proofs/'),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='category',
            field=models.CharField(choices=[('Children', 'Children'), ('Elderly', 'Elderly'), ('Mixed', 'Mixed'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg'), ('Any', 'Any')], default='Any', max_length=50),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='scout_photos/'),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ScoutBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
