# Generated by Django 6.0.3 on 2026-03-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deliverytask_is_verified_deliverytask_proof_after_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverytask',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='people_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='food_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-veg'), ('Any', 'Any')], default='Any', max_length=20),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='has_packaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='hygiene_declared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='max_holding_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_photos/'),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='pickup_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='last_verified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='needylocation',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Any', 'Any')], default='Any', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.needylocation'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='food_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tasks', to='core.foodlisting'),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Picked Up', 'Picked Up'), ('On Way', 'On Way'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Claimed', 'Claimed'), ('Picked Up', 'Picked Up'), ('Delivered', 'Delivered'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='needylocation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scoutbookmark',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('donation_accepted', 'Donation Accepted'), ('volunteer_nearby', 'Volunteer Nearby'), ('no_volunteer', 'No Volunteer Found'), ('new_donation_nearby', 'New Donation Nearby'), ('delivery_complete', 'Delivery Complete'), ('listing_expiring', 'Listing Expiring'), ('new_hotspot', 'New Hotspot Nearby')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.foodlisting')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.deliverytask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer')], default='donor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=50)),
                ('preferred_area', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
